import type { Metadata } from "next";
import "./globals.css";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Ilios",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname();
  const is2FAModal = pathname === "/auth/2fa";

  return (
    <>
      {children}
      {is2FAModal && <TwoFactorAuth />}
    </>
  );
}
