export default function CenteredBox() {
  return (
    <div className="fixed inset-0 flex items-center justify-center">
      <div className="max-w-[622px] max-h-[481px] border rounded-[20px] bg-[#EDF3FC] shadow-lg">
        {/* Content inside the box */}
        <h2 className="text-3xl text-blue-normal font-medium text-center">
          Two-Factor Authentication
        </h2>
        <p className="text-center mt-3 text-base text-[#171717] max-w-[439px] mx-auto">
          For your security, please enter the 2FA code sent to your email or
          generated by your authentication app.
        </p>

        <form action="">
          <h2>2FA</h2>
          input
        </form>
      </div>
    </div>
  );
}
